[lint]
select = ["ALL"]
ignore = [
	"COM812",
	"D203",
	"D213",
	"ISC001",
]

[lint.per-file-ignores]
"tests/**/*.py" = ["S101", "D", "ANN", "INP001"]
"**/__init__.py" = ["D104"]
"docs/gen_ref_pages.py" = ["INP001"]
