name: Release

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  release-container:
    uses: radiorabe/actions/.github/workflows/release-container.yaml@v0.19.1
    with:
      image: ghcr.io/radiorabe/minioevents
      name: minioevents
      display-name: Convert MinIO-Events into CloudEvents
      tags: minimal rhel9 ubi9 rabe minio kafka cloudevents
      cosign-base-image-only: false
  mkdocs:
    uses: radiorabe/actions/.github/workflows/release-mkdocs.yaml@v0.19.1
